#!/bin/sh
# Configuración de live-build para Antü Pro.
# Pensada para hardware potente: multinúcleo, GPU dedicada, SSD.
set -e

lb config noauto \
    --mode debian \
    --architectures "amd64" \
    --distribution "bookworm" \
    --binary-images "iso-hybrid" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --debian-installer "live" \
    --linux-flavours "amd64" \
    --iso-application "Antu Pro" \
    --iso-volume "ANTU_PRO" \
    --iso-publisher "Antu OS Project" \
    "${@}"
