[Icon Theme]
Name=Antü
Comment=Tema de íconos propio de Antü OS (skeuomórfico, paleta azul/cian)
Inherits=hicolor
Directories=256x256/places,256x256/devices,256x256/apps,48x48/places,48x48/devices,48x48/apps,24x24/places,24x24/devices,24x24/apps

[256x256/places]
Size=256
Context=Places
Type=Fixed

[256x256/devices]
Size=256
Context=Devices
Type=Fixed

[256x256/apps]
Size=256
Context=Applications
Type=Fixed

[48x48/places]
Size=48
Context=Places
Type=Fixed

[48x48/devices]
Size=48
Context=Devices
Type=Fixed

[48x48/apps]
Size=48
Context=Applications
Type=Fixed

[24x24/places]
Size=24
Context=Places
Type=Fixed

[24x24/devices]
Size=24
Context=Devices
Type=Fixed

[24x24/apps]
Size=24
Context=Applications
Type=Fixed
