#!/bin/sh
# Configuración de live-build para WinLux Standard.
# Pensada para uso doméstico/oficina en hardware equivalente a Windows 7+.
set -e

lb config noauto \
    --architectures "amd64" \
    --distribution "bookworm" \
    --binary-images "iso-hybrid" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --debian-installer "live" \
    --iso-application "WinLux Standard" \
    --iso-volume "WINLUX_STANDARD" \
    --iso-publisher "WinLux OS Project" \
    "${@}"
